version: '3.8'
services:
  db:
    image: postgres:16.8
    container_name: postgres_db
    environment:
      POSTGRES_DB: nodejs-template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      NODE_ENV: test
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: nodejs-template
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: 