services:
  postgres:
    image: postgres:16.8-alpine
    environment:
      POSTGRES_DB: nodejs-template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    environment:
      NODE_ENV: test
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: nodejs-template
      DB_USERNAME: postgres
      DB_PASSWORD: postgres_password
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: 